# Generated by Django 4.2.6 on 2023-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regPin', models.CharField(max_length=5)),
                ('admin', models.CharField(max_length=12)),
                ('urlNumCap', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('regGroupCap', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
