# Generated by Django 4.2.6 on 2023-10-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_registry_spendlimit_alter_registry_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
