# Generated by Django 4.2.6 on 2023-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_registry_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='regName',
            field=models.CharField(default=1, max_length=25, verbose_name='Registry Group Name:'),
            preserve_default=False,
        ),
    ]
