# Generated by Django 4.2.6 on 2023-11-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_registry_regname'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftgroups',
            name='registry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.registry'),
            preserve_default=False,
        ),
    ]
