# Generated by Django 4.2.6 on 2023-11-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_gift_giftrank_alter_registry_urlnumcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nogive',
            name='noGift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nogive_noGift', to=settings.AUTH_USER_MODEL, verbose_name='User to not pair with:'),
        ),
    ]
