# Generated by Django 4.2.6 on 2023-11-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_nogive_nogift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giftUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
