# Generated by Django 4.2.6 on 2023-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_gift_gifturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpair',
            name='regPin',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nogive',
            name='regPin',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
