# Generated by Django 4.2.6 on 2023-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_listpair_regpin_nogive_regpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giftUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
